# Task 3: Combining datasets to answer RQs

**Question:  How popular were the top most recent Kdramas around the world in the month of September 2026?**

## 1. Assembling Top 10 Shows with Highest Ratings

Goal: produce a list of article names.

First, I looked up the top shows with the highest ratings manually and assembled a list:

1. Teach you a lesson 9.0 
2. Four Hands, Two Sonatas 8.7
3. Bloodhounds Season 2 8.7
4. Agent Kim Reactivated 8.6
5. Yumi's Cells Seaons 3 8.6
6. A Shop for Killers Season 2 8.5
7. The Wonderfools 8.5 
8. The legend of kitchen soldier 8.5
9. we are all trying here 8,5
10. A Bona Fide Killer 8.4

Next, we need a list of Wikipedia names. I also did this manually by looking at the unique URL of each title.

In [1]:
names = ['Teach_You_a_Lesson', 'Four_Hands,_Two_Sonatas', 'Bloodhounds_(TV_series)', 
         'Agent_Kim_Reactivated', 'Yumi%27s_Cells', 'A_Shop_for_Killers',
         'The_Wonderfools', 'The_Legend_of_Kitchen_Soldier','We_Are_All_Trying_Here',
         'A_Bona_Fide_Killer']

## 2. Retrieve Wiki Daily Pageviews (one day first)

The idea is to get the pageviews tsv of each day in September. For each day, search the df with the query (10 in total, 1 for each drama).

Let's just start with the example from the Wednesday notebook.

In [11]:
import pandas as pd
import requests, io

url = "https://analytics.wikimedia.org/published/datasets/country_project_page/2026-09-29.tsv"

headers = {'User-Agent': 'MyDataAnalysisScript/1.0 (contact: wendywellesley@gmail.com)'}
response = requests.get(url, headers=headers)

In [12]:
df = pd.read_csv(io.StringIO(response.text), sep='\t', header=None)
df.head()

,0,1,2,3,4,5,6
0,Algeria,DZ,ar.wikipedia,3947,Ø°ÙØ§Ø¡_Ø§ØµØ·ÙØ§Ø¹Ù,Q11660,122
1,Argentina,AR,es.wikipedia,3094323,Juana_Viale,Q9016209,115
2,Argentina,AR,es.wikipedia,327209,JosÃ©_Mourinho,Q79983,114
3,Argentina,AR,es.wikipedia,4449701,Copa_Libertadores,Q184795,386
4,Argentina,AR,es.wikipedia,47340,Thomas_Sankara,Q202155,119

Let's rename these columns.

In [13]:
columns = ['country', 'country-code', 'wiki', 'page_id', 'article', 'qid', 'views']
df.columns = columns

In [14]:
df.head()

,country,country-code,wiki,page_id,article,qid,views
0,Algeria,DZ,ar.wikipedia,3947,Ø°ÙØ§Ø¡_Ø§ØµØ·ÙØ§Ø¹Ù,Q11660,122
1,Argentina,AR,es.wikipedia,3094323,Juana_Viale,Q9016209,115
2,Argentina,AR,es.wikipedia,327209,JosÃ©_Mourinho,Q79983,114
3,Argentina,AR,es.wikipedia,4449701,Copa_Libertadores,Q184795,386
4,Argentina,AR,es.wikipedia,47340,Thomas_Sankara,Q202155,119

In [15]:
df.shape

(293466, 7)

Try to filter this df for specific queries:

In [7]:
query = names[0]

filtered_df = df[
    df['article'].str.contains(query, case=False, na=False)
]

filtered_df.head()

,country,country-code,wiki,page_id,article,qid,views
5054,Singapore,SG,en.wikipedia,79560156,Teach_You_a_Lesson,Q137844128,111
8713,United States,US,en.wikipedia,79560156,Teach_You_a_Lesson,Q137844128,369
38494,India,IN,en.wikipedia,79560156,Teach_You_a_Lesson,Q137844128,244
75513,Indonesia,ID,en.wikipedia,79560156,Teach_You_a_Lesson,Q137844128,129
87615,Philippines,PH,en.wikipedia,79560156,Teach_You_a_Lesson,Q137844128,139

In [10]:
filtered_df.shape

(5, 7)

This means that on this day, only five countries looked this kdrama up on Wikipedia, and each country had a certain number of views.

## 3. Set up loop for URL updates to capture entire September

This is a simple but important step! We will automate the collection of all tsvs in September by making the URL a f-string.

In [29]:
sept_urls = []
for i in range(1,31):  # 30 days in september
    if i < 10:
        date = f"2026-09-0{i}"
    else:
        date = f"2026-09-{i}"
    url = f"https://analytics.wikimedia.org/published/datasets/country_project_page/{date}.tsv"
    sept_urls.append(url)

In [30]:
sept_urls[:5]

['https://analytics.wikimedia.org/published/datasets/country_project_page/2026-09-01.tsv',
 'https://analytics.wikimedia.org/published/datasets/country_project_page/2026-09-02.tsv',
 'https://analytics.wikimedia.org/published/datasets/country_project_page/2026-09-03.tsv',
 'https://analytics.wikimedia.org/published/datasets/country_project_page/2026-09-04.tsv',
 'https://analytics.wikimedia.org/published/datasets/country_project_page/2026-09-05.tsv']

## 4.

Goal: columns = date, country, article, pageviews; each row is one country one article.

Pseudocode for the full block of code:

create: kdrama_df    
for every url:    
-> for every query:   
--> create a column for date that is just the date  
--> merge the smaller filtered_df with the larger kdrama_df

In [26]:
columns = ['country', 'country-code', 'wiki', 'page_id', 'article', 'qid', 'views']
full_df = pd.DataFrame()

for i in range(10, len(sept_urls)):
    date = f"2026-09-{i}"
    url = sept_urls[i]

    # get the daily tsv first
    headers = {'User-Agent': 'MyDataAnalysisScript/1.0 (contact: wendywellesley@gmail.com)'}
    response = requests.get(url, headers=headers)

    # read in as df
    day_df = pd.read_csv(io.StringIO(response.text), sep='\t', header=None)
    day_df.columns = columns

    # add a column for date
    day_df['date'] = date

    for j in range(1, len(names)): # each kdrama
        query = names[j]
        filtered_df = day_df[
            day_df['article'].str.contains(query, case=False, na=False)]
        full_df = pd.concat([full_df, filtered_df], axis=1)

                    0   1                 2         3  \
0           Argentina  AR      es.wikipedia  11526564
1           Argentina  AR      es.wikipedia   3094323
2           Argentina  AR      es.wikipedia    327209
3           Argentina  AR      es.wikipedia   4449701
4           Argentina  AR      es.wikipedia   5640452
...               ...  ..               ...       ...
304478  United States  US  simple.wikipedia    525641
304479  United States  US      zh.wikipedia    124440
304480  United States  US      zh.wikipedia       317
304481  United States  US      zh.wikipedia     86555
304482        Uruguay  UY      es.wikipedia  11552922

                                         4           5    6
0       La_invitaciÃ³n_(pelÃ­cula_de_2026)  Q134083296  429
1                              Juana_Viale    Q9016209  181
2                           JosÃ©_Mourinho      Q79983  153
3            Copa_Libertadores_de_AmÃ©rica     Q184795  716
4                          Michael_Jackson       Q2831  244
...                                    ...         ...  ...
304478                    Shameful_Secrets         NaN  157
304479                           èä¸æ³¢     Q553682  113
304480                        äººå·¥æºè½      Q11660   92
304481                              æ±é     Q236017  211
304482               Copa_AUF_Uruguay_2026  Q140655962  133

[304483 rows x 7 columns]

/var/folders/f6/71_23hqx2gv3g0x_h49kbbf80000gn/T/ipykernel_10388/2281861999.py:23: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  day_df['article'].str.contains(query, case=False, na=False)]

                    0   1                 2         3  \
0             Algeria  DZ      ar.wikipedia   9046254
1           Argentina  AR      en.wikipedia  80387746
2           Argentina  AR      es.wikipedia  11526564
3           Argentina  AR      es.wikipedia   3094323
4           Argentina  AR      es.wikipedia    327209
...               ...  ..               ...       ...
318185  United States  US      or.wikipedia      1594
318186  United States  US     ru.wikivoyage      8876
318187  United States  US  simple.wikipedia    525641
318188  United States  US      zh.wikipedia     86555
318189        Uruguay  UY      es.wikipedia  11552922

                                                        4           5    6
0                                   Ø¥ÙÙÙÙ_ÙØ®ØªÙÙ   Q64168758  156
1                                         Inde_Navarrette  Q106932301  119
2                      La_invitaciÃ³n_(pelÃ­cula_de_2026)  Q134083296  757
3                                             Juana_Viale    Q9016209  123
4                                          JosÃ©_Mourinho      Q79983  263
...                                                   ...         ...  ...
318185              à¬ªà­à¬°à¬§à¬¾à¬¨_à¬ªà­à¬·à­à¬ à¬¾       Q5296  603
318186  ÐÑÐ»ÑÑÑÑÐ½Ð¾Ðµ_Ð½Ð°ÑÐ»ÐµÐ´Ð¸Ðµ_Ð Ð¾ÑÑ...   Q16354789  193
318187                                   Shameful_Secrets         NaN  211
318188                                             æ±é     Q236017  159
318189                              Copa_AUF_Uruguay_2026  Q140655962   97

[318190 rows x 7 columns]

/var/folders/f6/71_23hqx2gv3g0x_h49kbbf80000gn/T/ipykernel_10388/2281861999.py:23: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  day_df['article'].str.contains(query, case=False, na=False)]

                    0   1              2         3  \
0           Argentina  AR   es.wikipedia  11526564
1           Argentina  AR   es.wikipedia   2934940
2           Argentina  AR   es.wikipedia   3094323
3           Argentina  AR   es.wikipedia    327209
4           Argentina  AR   es.wikipedia   4449701
...               ...  ..            ...       ...
340091  United States  US  ru.wikivoyage      8876
340092  United States  US  ru.wikivoyage       999
340093  United States  US   zh.wikipedia    124440
340094  United States  US   zh.wikipedia     86555
340095        Uruguay  UY   es.wikipedia    148834

                                                        4           5    6
0                      La_invitaciÃ³n_(pelÃ­cula_de_2026)  Q134083296  716
1                                      VÃ­ctor_Sarasqueta    Q5671904  116
2                                             Juana_Viale    Q9016209  464
3                                          JosÃ©_Mourinho      Q79983  164
4                           Copa_Libertadores_de_AmÃ©rica     Q184795  297
...                                                   ...         ...  ...
340091  ÐÑÐ»ÑÑÑÑÐ½Ð¾Ðµ_Ð½Ð°ÑÐ»ÐµÐ´Ð¸Ðµ_Ð Ð¾ÑÑ...   Q16354789  106
340092                                         ÐÐ°ÑÐ¸Ð¶         Q90  229
340093                                          èä¸æ³¢     Q553682  105
340094                                             æ±é     Q236017  177
340095                              Julio_CÃ©sar_Falcioni    Q1332586  131

[340096 rows x 7 columns]

/var/folders/f6/71_23hqx2gv3g0x_h49kbbf80000gn/T/ipykernel_10388/2281861999.py:23: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  day_df['article'].str.contains(query, case=False, na=False)]

                    0   1                 2         3  \
0           Argentina  AR      es.wikipedia  11526564
1           Argentina  AR      es.wikipedia   3094323
2           Argentina  AR      es.wikipedia    327209
3           Argentina  AR      es.wikipedia   4449701
4           Argentina  AR      es.wikipedia     49144
...               ...  ..               ...       ...
311539  United States  US  simple.wikipedia    129576
311540  United States  US      zh.wikipedia    124440
311541  United States  US      zh.wikipedia   6172949
311542  United States  US      zh.wikipedia     86555
311543        Uruguay  UY      es.wikipedia  11552922

                                         4           5    6
0       La_invitaciÃ³n_(pelÃ­cula_de_2026)  Q134083296  241
1                              Juana_Viale    Q9016209  197
2                           JosÃ©_Mourinho      Q79983  102
3            Copa_Libertadores_de_AmÃ©rica     Q184795  319
4                                    BakÃº       Q9248  134
...                                    ...         ...  ...
311539            List_of_cities_in_France         NaN  124
311540                           èä¸æ³¢     Q553682  174
311541                           ç¸æ¾¤å   Q43431475  106
311542                              æ±é     Q236017  175
311543               Copa_AUF_Uruguay_2026  Q140655962  142

[311544 rows x 7 columns]

/var/folders/f6/71_23hqx2gv3g0x_h49kbbf80000gn/T/ipykernel_10388/2281861999.py:23: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  day_df['article'].str.contains(query, case=False, na=False)]

                    0   1             2         3  \
0           Argentina  AR  es.wikipedia  11526564
1           Argentina  AR  es.wikipedia   3094323
2           Argentina  AR  es.wikipedia    327209
3           Argentina  AR  es.wikipedia   4449701
4           Argentina  AR  es.wikipedia   5640452
...               ...  ..           ...       ...
300332  United States  US  zh.wikipedia    124440
300333  United States  US  zh.wikipedia       317
300334  United States  US  zh.wikipedia     86555
300335        Uruguay  UY  es.wikipedia  11552922
300336        Uruguay  UY  es.wikipedia      3623

                                         4           5    6
0       La_invitaciÃ³n_(pelÃ­cula_de_2026)  Q134083296   90
1                              Juana_Viale    Q9016209  129
2                           JosÃ©_Mourinho      Q79983  145
3            Copa_Libertadores_de_AmÃ©rica     Q184795  602
4                          Michael_Jackson       Q2831  225
...                                    ...         ...  ...
300332                           èä¸æ³¢     Q553682  111
300333                        äººå·¥æºè½      Q11660  124
300334                              æ±é     Q236017  167
300335               Copa_AUF_Uruguay_2026  Q140655962  101
300336                    15_de_septiembre       Q2846   90

[300337 rows x 7 columns]

/var/folders/f6/71_23hqx2gv3g0x_h49kbbf80000gn/T/ipykernel_10388/2281861999.py:23: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  day_df['article'].str.contains(query, case=False, na=False)]

                    0   1              2         3  \
0             Algeria  DZ   ar.wikipedia      3947
1             Algeria  DZ   fr.wikipedia    200268
2           Argentina  AR   es.wikipedia  11526564
3           Argentina  AR   es.wikipedia   3094323
4           Argentina  AR   es.wikipedia   4449701
...               ...  ..            ...       ...
299455  United States  US  ru.wikivoyage       999
299456  United States  US   zh.wikipedia    124440
299457  United States  US   zh.wikipedia       317
299458  United States  US   zh.wikipedia     86555
299459        Uruguay  UY   es.wikipedia  11552922

                                         4           5     6
0                  Ø°ÙØ§Ø¡_Ø§ØµØ·ÙØ§Ø¹Ù      Q11660    97
1            Grand_Theft_Auto:_San_Andreas      Q83265   102
2       La_invitaciÃ³n_(pelÃ­cula_de_2026)  Q134083296   134
3                              Juana_Viale    Q9016209   105
4            Copa_Libertadores_de_AmÃ©rica     Q184795  1151
...                                    ...         ...   ...
299455                          ÐÐ°ÑÐ¸Ð¶         Q90   183
299456                           èä¸æ³¢     Q553682   108
299457                        äººå·¥æºè½      Q11660    95
299458                              æ±é     Q236017   198
299459               Copa_AUF_Uruguay_2026  Q140655962   257

[299460 rows x 7 columns]

/var/folders/f6/71_23hqx2gv3g0x_h49kbbf80000gn/T/ipykernel_10388/2281861999.py:23: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  day_df['article'].str.contains(query, case=False, na=False)]

                    0   1             2         3  \
0           Argentina  AR  es.wikipedia  11526564
1           Argentina  AR  es.wikipedia   4449701
2           Argentina  AR  es.wikipedia   5640452
3           Argentina  AR  es.wikipedia   8008545
4           Argentina  AR  es.wikipedia    834992
...               ...  ..           ...       ...
300227  United States  US  zh.wikipedia       317
300228  United States  US  zh.wikipedia   6172949
300229  United States  US  zh.wikipedia    708680
300230  United States  US  zh.wikipedia     86555
300231        Uruguay  UY  es.wikipedia  11552922

                                         4           5     6
0       La_invitaciÃ³n_(pelÃ­cula_de_2026)  Q134083296   102
1            Copa_Libertadores_de_AmÃ©rica     Q184795  2534
2                          Michael_Jackson       Q2831   192
3                      Alexis_Mac_Allister   Q33297140   160
4                             Mohamed_Atta     Q110067   114
...                                    ...         ...   ...
300227                        äººå·¥æºè½      Q11660   126
300228                           ç¸æ¾¤å   Q43431475    91
300229                           é­æ±è¬    Q8272916    92
300230                              æ±é     Q236017   156
300231               Copa_AUF_Uruguay_2026  Q140655962   265

[300232 rows x 7 columns]

/var/folders/f6/71_23hqx2gv3g0x_h49kbbf80000gn/T/ipykernel_10388/2281861999.py:23: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  day_df['article'].str.contains(query, case=False, na=False)]

                    0   1             2         3  \
0           Argentina  AR  es.wikipedia   3094323
1           Argentina  AR  es.wikipedia    327209
2           Argentina  AR  es.wikipedia   4449701
3           Argentina  AR  es.wikipedia   5640452
4           Argentina  AR  es.wikipedia   8008545
...               ...  ..           ...       ...
294725  United States  US  zh.wikipedia    124440
294726  United States  US  zh.wikipedia       317
294727  United States  US  zh.wikipedia   6172949
294728  United States  US  zh.wikipedia     86555
294729        Uruguay  UY  es.wikipedia  11552922

                                    4           5     6
0                         Juana_Viale    Q9016209   146
1                      JosÃ©_Mourinho      Q79983   111
2       Copa_Libertadores_de_AmÃ©rica     Q184795  1521
3                     Michael_Jackson       Q2831   213
4                 Alexis_Mac_Allister   Q33297140   101
...                               ...         ...   ...
294725                      èä¸æ³¢     Q553682   118
294726                   äººå·¥æºè½      Q11660   125
294727                      ç¸æ¾¤å   Q43431475   105
294728                         æ±é     Q236017   154
294729          Copa_AUF_Uruguay_2026  Q140655962   219

[294730 rows x 7 columns]

/var/folders/f6/71_23hqx2gv3g0x_h49kbbf80000gn/T/ipykernel_10388/2281861999.py:23: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  day_df['article'].str.contains(query, case=False, na=False)]

                    0   1                 2         3  \
0           Argentina  AR      es.wikipedia  11526564
1           Argentina  AR      es.wikipedia   3094323
2           Argentina  AR      es.wikipedia    327209
3           Argentina  AR      es.wikipedia   4449701
4           Argentina  AR      es.wikipedia   5640452
...               ...  ..               ...       ...
305906  United States  US     kaj.wikipedia       774
305907  United States  US      or.wikipedia      1594
305908  United States  US     ru.wikivoyage      8876
305909  United States  US  simple.wikipedia    129576
305910  United States  US      zh.wikipedia     86555

                                                        4           5    6
0                      La_invitaciÃ³n_(pelÃ­cula_de_2026)  Q134083296  124
1                                             Juana_Viale    Q9016209  405
2                                          JosÃ©_Mourinho      Q79983  197
3                           Copa_Libertadores_de_AmÃ©rica     Q184795  514
4                                         Michael_Jackson       Q2831  263
...                                                   ...         ...  ...
305906                               AÌ±gbaÌ±dang_KaÌ±zzu       Q5296  104
305907              à¬ªà­à¬°à¬§à¬¾à¬¨_à¬ªà­à¬·à­à¬ à¬¾       Q5296  266
305908  ÐÑÐ»ÑÑÑÑÐ½Ð¾Ðµ_Ð½Ð°ÑÐ»ÐµÐ´Ð¸Ðµ_Ð Ð¾ÑÑ...   Q16354789  159
305909                           List_of_cities_in_France         NaN  102
305910                                             æ±é     Q236017  164

[305911 rows x 7 columns]

/var/folders/f6/71_23hqx2gv3g0x_h49kbbf80000gn/T/ipykernel_10388/2281861999.py:23: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  day_df['article'].str.contains(query, case=False, na=False)]

                    0   1              2         3  \
0           Argentina  AR   es.wikipedia  10378593
1           Argentina  AR   es.wikipedia  11526564
2           Argentina  AR   es.wikipedia  11602517
3           Argentina  AR   es.wikipedia    229324
4           Argentina  AR   es.wikipedia   3094323
...               ...  ..            ...       ...
329087  United States  US  ru.wikivoyage      8876
329088  United States  US   zh.wikipedia    124440
329089  United States  US   zh.wikipedia   6172949
329090  United States  US   zh.wikipedia     86555
329091        Uruguay  UY   es.wikipedia    343744

                                                        4           5    6
0                   Â¿EstÃ¡s_ahÃ­,_Dios?_Soy_yo,_Margaret  Q106448550  111
1                      La_invitaciÃ³n_(pelÃ­cula_de_2026)  Q134083296  112
2                                             Susy_Aponte         NaN  443
3                                    RÃ­o_Cuarto_(ciudad)     Q983451  139
4                                             Juana_Viale    Q9016209  626
...                                                   ...         ...  ...
329087  ÐÑÐ»ÑÑÑÑÐ½Ð¾Ðµ_Ð½Ð°ÑÐ»ÐµÐ´Ð¸Ðµ_Ð Ð¾ÑÑ...   Q16354789  225
329088                                          èä¸æ³¢     Q553682   99
329089                                          ç¸æ¾¤å   Q43431475  104
329090                                             æ±é     Q236017  211
329091                                          Vicentico    Q2474993   97

[329092 rows x 7 columns]

/var/folders/f6/71_23hqx2gv3g0x_h49kbbf80000gn/T/ipykernel_10388/2281861999.py:23: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  day_df['article'].str.contains(query, case=False, na=False)]

                    0   1             2         3  \
0           Argentina  AR  es.wikipedia    110761
1           Argentina  AR  es.wikipedia  11526564
2           Argentina  AR  es.wikipedia  11602517
3           Argentina  AR  es.wikipedia    229324
4           Argentina  AR  es.wikipedia   3094323
...               ...  ..           ...       ...
309338  United States  US  zh.wikipedia   1496598
309339  United States  US  zh.wikipedia       317
309340  United States  US  zh.wikipedia   6172949
309341  United States  US  zh.wikipedia     86555
309342        Uruguay  UY  es.wikipedia  11552922

                                         4           5     6
0                         Orlando_Letelier     Q443777    96
1       La_invitaciÃ³n_(pelÃ­cula_de_2026)  Q134083296    98
2                              Susy_Aponte         NaN  1960
3                     RÃ­o_Cuarto_(ciudad)     Q983451   113
4                              Juana_Viale    Q9016209   285
...                                    ...         ...   ...
309338                           é­å¤å    Q7929529    92
309339                        äººå·¥æºè½      Q11660   143
309340                           ç¸æ¾¤å   Q43431475   151
309341                              æ±é     Q236017   193
309342               Copa_AUF_Uruguay_2026  Q140655962    91

[309343 rows x 7 columns]

/var/folders/f6/71_23hqx2gv3g0x_h49kbbf80000gn/T/ipykernel_10388/2281861999.py:23: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  day_df['article'].str.contains(query, case=False, na=False)]

                    0   1             2         3  \
0           Argentina  AR  es.wikipedia  11602517
1           Argentina  AR  es.wikipedia    229324
2           Argentina  AR  es.wikipedia   3094323
3           Argentina  AR  es.wikipedia    327209
4           Argentina  AR  es.wikipedia   4449701
...               ...  ..           ...       ...
299381  United States  US  or.wikipedia      1594
299382  United States  US  zh.wikibooks     34912
299383  United States  US  zh.wikipedia   7079184
299384  United States  US  zh.wikipedia     86555
299385        Uruguay  UY  es.wikipedia  11552922

                                                        4           5    6
0                                             Susy_Aponte         NaN  438
1                                    RÃ­o_Cuarto_(ciudad)     Q983451  113
2                                             Juana_Viale    Q9016209  159
3                                          JosÃ©_Mourinho      Q79983  131
4                           Copa_Libertadores_de_AmÃ©rica     Q184795  359
...                                                   ...         ...  ...
299381              à¬ªà­à¬°à¬§à¬¾à¬¨_à¬ªà­à¬·à­à¬ à¬¾       Q5296  349
299382       ç°ä»£æ åæ±è¯­/ç»ªè®º/ç°ä»£æ±è¯­æ¦è¯´         NaN  342
299383  2020å¹´æ®éé«ç­å­¦æ ¡æçå¨å½ç»ä¸èè¯   Q97016928  141
299384                                             æ±é     Q236017  124
299385                              Copa_AUF_Uruguay_2026  Q140655962  165

[299386 rows x 7 columns]

/var/folders/f6/71_23hqx2gv3g0x_h49kbbf80000gn/T/ipykernel_10388/2281861999.py:23: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  day_df['article'].str.contains(query, case=False, na=False)]

                     0   1                 2         3  \
0       American Samoa  AS      en.wikipedia  81773588
1            Argentina  AR      es.wikipedia  11602517
2            Argentina  AR      es.wikipedia    229324
3            Argentina  AR      es.wikipedia    327209
4            Argentina  AR      es.wikipedia   4449701
...                ...  ..               ...       ...
299766   United States  US  simple.wikipedia    129576
299767   United States  US      sv.wikiquote         2
299768   United States  US      zh.wikipedia    124440
299769   United States  US      zh.wikipedia     86555
299770         Uruguay  UY      es.wikipedia  11552922

                                    4           5    6
0                Great_Yarmouth_First  Q138309755   90
1                         Susy_Aponte         NaN  148
2                RÃ­o_Cuarto_(ciudad)     Q983451  103
3                      JosÃ©_Mourinho      Q79983  123
4       Copa_Libertadores_de_AmÃ©rica     Q184795  304
...                               ...         ...  ...
299766       List_of_cities_in_France         NaN  130
299767                      Huvudsida       Q5296  106
299768                      èä¸æ³¢     Q553682  151
299769                         æ±é     Q236017  169
299770          Copa_AUF_Uruguay_2026  Q140655962  182

[299771 rows x 7 columns]

/var/folders/f6/71_23hqx2gv3g0x_h49kbbf80000gn/T/ipykernel_10388/2281861999.py:23: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  day_df['article'].str.contains(query, case=False, na=False)]

                    0   1             2         3  \
0           Argentina  AR  es.wikipedia   3094323
1           Argentina  AR  es.wikipedia   4449701
2           Argentina  AR  es.wikipedia     49144
3           Argentina  AR  es.wikipedia   5640452
4           Argentina  AR  es.wikipedia      7884
...               ...  ..           ...       ...
290770  United States  US  or.wikipedia      1594
290771  United States  US  sv.wikiquote         2
290772  United States  US  zh.wikipedia    124440
290773  United States  US  zh.wikipedia     86555
290774        Uruguay  UY  es.wikipedia  11552922

                                            4           5    6
0                                 Juana_Viale    Q9016209  121
1               Copa_Libertadores_de_AmÃ©rica     Q184795  267
2                                       BakÃº       Q9248  831
3                             Michael_Jackson       Q2831  185
4                                   Primavera       Q1312   94
...                                       ...         ...  ...
290770  à¬ªà­à¬°à¬§à¬¾à¬¨_à¬ªà­à¬·à­à¬ à¬¾       Q5296  793
290771                              Huvudsida       Q5296   97
290772                              èä¸æ³¢     Q553682  103
290773                                 æ±é     Q236017  147
290774                  Copa_AUF_Uruguay_2026  Q140655962  554

[290775 rows x 7 columns]

/var/folders/f6/71_23hqx2gv3g0x_h49kbbf80000gn/T/ipykernel_10388/2281861999.py:23: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  day_df['article'].str.contains(query, case=False, na=False)]

                    0   1             2         3  \
0             Algeria  DZ  ar.wikipedia      3947
1           Argentina  AR  es.wikipedia   2928144
2           Argentina  AR  es.wikipedia   3094323
3           Argentina  AR  es.wikipedia    327209
4           Argentina  AR  es.wikipedia   4449701
...               ...  ..           ...       ...
290576  United States  US  sv.wikiquote         2
290577  United States  US  zh.wikibooks     34912
290578  United States  US  zh.wikipedia    124440
290579  United States  US  zh.wikipedia     86555
290580        Uruguay  UY  es.wikipedia  11552922

                                                   4           5    6
0                            Ø°ÙØ§Ø¡_Ø§ØµØ·ÙØ§Ø¹Ù      Q11660  137
1                                       Ronnie_Arias    Q6111981  208
2                                        Juana_Viale    Q9016209  139
3                                     JosÃ©_Mourinho      Q79983  126
4                      Copa_Libertadores_de_AmÃ©rica     Q184795  220
...                                              ...         ...  ...
290576                                     Huvudsida       Q5296   98
290577  ç°ä»£æ åæ±è¯­/ç»ªè®º/ç°ä»£æ±è¯­æ¦è¯´         NaN  162
290578                                     èä¸æ³¢     Q553682   95
290579                                        æ±é     Q236017  154
290580                         Copa_AUF_Uruguay_2026  Q140655962  322

[290581 rows x 7 columns]

/var/folders/f6/71_23hqx2gv3g0x_h49kbbf80000gn/T/ipykernel_10388/2281861999.py:23: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  day_df['article'].str.contains(query, case=False, na=False)]

                    0   1             2         3  \
0             Albania  AL  en.wikipedia  18514671
1             Algeria  DZ  ar.wikipedia      3947
2           Argentina  AR  es.wikipedia   3094323
3           Argentina  AR  es.wikipedia    327209
4           Argentina  AR  es.wikipedia   4449701
...               ...  ..           ...       ...
306028  United States  US  sv.wikiquote         2
306029  United States  US  zh.wikibooks     34912
306030  United States  US  zh.wikipedia     31225
306031  United States  US  zh.wikipedia     86555
306032        Uruguay  UY  es.wikipedia  11552922

                                                   4           5    6
0                                             Roblox     Q692989  290
1                            Ø°ÙØ§Ø¡_Ø§ØµØ·ÙØ§Ø¹Ù      Q11660  311
2                                        Juana_Viale    Q9016209  100
3                                     JosÃ©_Mourinho      Q79983  121
4                      Copa_Libertadores_de_AmÃ©rica     Q184795  186
...                                              ...         ...  ...
306028                                     Huvudsida       Q5296  105
306029  ç°ä»£æ åæ±è¯­/ç»ªè®º/ç°ä»£æ±è¯­æ¦è¯´         NaN  234
306030                                  èåä¸­å­¦    Q8049064  111
306031                                        æ±é     Q236017  168
306032                         Copa_AUF_Uruguay_2026  Q140655962   99

[306033 rows x 7 columns]

/var/folders/f6/71_23hqx2gv3g0x_h49kbbf80000gn/T/ipykernel_10388/2281861999.py:23: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  day_df['article'].str.contains(query, case=False, na=False)]

                    0   1             2         3  \
0           Argentina  AR  es.wikipedia  11526564
1           Argentina  AR  es.wikipedia   1358593
2           Argentina  AR  es.wikipedia   3094323
3           Argentina  AR  es.wikipedia    327209
4           Argentina  AR  es.wikipedia   4449701
...               ...  ..           ...       ...
327553  United States  US  zh.wikibooks     34912
327554  United States  US  zh.wikipedia       317
327555  United States  US  zh.wikipedia   6172949
327556  United States  US  zh.wikipedia     86555
327557        Uruguay  UY  es.wikipedia  11552922

                                                   4           5    6
0                 La_invitaciÃ³n_(pelÃ­cula_de_2026)  Q134083296  107
1                                     SusÃº_Pecoraro    Q7649867  295
2                                        Juana_Viale    Q9016209  415
3                                     JosÃ©_Mourinho      Q79983  104
4                      Copa_Libertadores_de_AmÃ©rica     Q184795  276
...                                              ...         ...  ...
327553  ç°ä»£æ åæ±è¯­/ç»ªè®º/ç°ä»£æ±è¯­æ¦è¯´         NaN  336
327554                                  äººå·¥æºè½      Q11660  183
327555                                     ç¸æ¾¤å   Q43431475  107
327556                                        æ±é     Q236017  190
327557                         Copa_AUF_Uruguay_2026  Q140655962  111

[327558 rows x 7 columns]

/var/folders/f6/71_23hqx2gv3g0x_h49kbbf80000gn/T/ipykernel_10388/2281861999.py:23: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  day_df['article'].str.contains(query, case=False, na=False)]

                    0   1             2         3  \
0           Argentina  AR  es.wikipedia  11526564
1           Argentina  AR  es.wikipedia   3094323
2           Argentina  AR  es.wikipedia   4449701
3           Argentina  AR  es.wikipedia     47340
4           Argentina  AR  es.wikipedia     49144
...               ...  ..           ...       ...
310805  United States  US  so.wikipedia     32143
310806  United States  US  zh.wikipedia    124440
310807  United States  US  zh.wikipedia   3016361
310808  United States  US  zh.wikipedia     86555
310809        Uruguay  UY  es.wikipedia  11552922

                                         4           5    6
0       La_invitaciÃ³n_(pelÃ­cula_de_2026)  Q134083296   94
1                              Juana_Viale    Q9016209  142
2            Copa_Libertadores_de_AmÃ©rica     Q184795  274
3                           Thomas_Sankara     Q202155  142
4                                    BakÃº       Q9248  108
...                                    ...         ...  ...
310805  Jabhadda_Xoraynta_Soomaali_Galbeed    Q1462545  105
310806                           èä¸æ³¢     Q553682  145
310807         è®æèåå¹³ä½é ä¸­ç°   Q14608233   95
310808                              æ±é     Q236017  248
310809               Copa_AUF_Uruguay_2026  Q140655962   99

[310810 rows x 7 columns]

/var/folders/f6/71_23hqx2gv3g0x_h49kbbf80000gn/T/ipykernel_10388/2281861999.py:23: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  day_df['article'].str.contains(query, case=False, na=False)]

                    0   1             2         3                        4  \
0             Algeria  DZ  ar.wikipedia      3947  Ø°ÙØ§Ø¡_Ø§ØµØ·ÙØ§Ø¹Ù
1           Argentina  AR  es.wikipedia   3094323              Juana_Viale
2           Argentina  AR  es.wikipedia    327209           JosÃ©_Mourinho
3           Argentina  AR  es.wikipedia   4449701        Copa_Libertadores
4           Argentina  AR  es.wikipedia     47340           Thomas_Sankara
...               ...  ..           ...       ...                      ...
293461  United States  US  zh.wikipedia    124440                èä¸æ³¢
293462  United States  US  zh.wikipedia       317             äººå·¥æºè½
293463  United States  US  zh.wikipedia   6331946                é§é¾å¨
293464  United States  US  zh.wikipedia     86555                   æ±é
293465        Uruguay  UY  es.wikipedia  11552922    Copa_AUF_Uruguay_2026

                 5    6
0           Q11660  122
1         Q9016209  115
2           Q79983  114
3          Q184795  386
4          Q202155  119
...            ...  ...
293461     Q553682   97
293462      Q11660   98
293463   Q60991613  159
293464     Q236017  171
293465  Q140655962  125

[293466 rows x 7 columns]

/var/folders/f6/71_23hqx2gv3g0x_h49kbbf80000gn/T/ipykernel_10388/2281861999.py:23: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  day_df['article'].str.contains(query, case=False, na=False)]

                    0   1             2         3  \
0             Algeria  DZ  ar.wikipedia      3947
1           Argentina  AR  es.wikipedia  11609897
2           Argentina  AR  es.wikipedia   3094323
3           Argentina  AR  es.wikipedia    327209
4           Argentina  AR  es.wikipedia   4449701
...               ...  ..           ...       ...
285746  United States  US  zh.wikipedia   5799092
285747  United States  US  zh.wikipedia   6331946
285748  United States  US  zh.wikipedia     86555
285749  United States  US  zh.wikipedia   9622536
285750        Uruguay  UY  es.wikipedia  11552922

                                                  4           5     6
0                           Ø°ÙØ§Ø¡_Ø§ØµØ·ÙØ§Ø¹Ù      Q11660    95
1                                 Jhon_Jairo_Torres         NaN   182
2                                       Juana_Viale    Q9016209  4958
3                                    JosÃ©_Mourinho      Q79983   110
4                     Copa_Libertadores_de_AmÃ©rica     Q184795   295
...                                             ...         ...   ...
285746                              é¦ç¾ç¹å¥å¸       Q8684    91
285747                                    é§é¾å¨   Q60991613   420
285748                                       æ±é     Q236017   160
285749  2026å¹´WTTä¸­å½å¤§æ»¡è´¯å¥³å­åææ¯èµ         NaN    96
285750                        Copa_AUF_Uruguay_2026  Q140655962   281

[285751 rows x 7 columns]

/var/folders/f6/71_23hqx2gv3g0x_h49kbbf80000gn/T/ipykernel_10388/2281861999.py:23: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  day_df['article'].str.contains(query, case=False, na=False)]

In [28]:
full_df.tail()

,country,country-code,wiki,page_id,article,qid,views,date,country,country-code,...,views,date,country,country-code,wiki,page_id,article,qid,views,date
26086,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132138,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76924,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Philippines,PH,en.wikipedia,83488921.0,A_Bona_Fide_Killer,Q139411314,131.0,2026-09-29
169926,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,India,IN,en.wikipedia,83488921.0,A_Bona_Fide_Killer,Q139411314,94.0,2026-09-29
232718,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,United States,US,en.wikipedia,83488921.0,A_Bona_Fide_Killer,Q139411314,250.0,2026-09-29